development:
  adapter: postgresql
  encoding: unicode
  database: songz_development
  pool: 5
  username: postgres
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: songz_production
  pool: 5
  username: postgres
  password: 